default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: dinner_time_development

test:
  <<: *default
  database: dinner_time_test
